-- Butterflies.ai demo schema. Run this once in Supabase SQL Editor.
create table if not exists public.meetings (
  id bigint generated by default as identity primary key,
  title text not null,
  date timestamptz not null default now(),
  duration integer not null default 30,
  summary text not null default '',
  key_topics jsonb not null default '[]'::jsonb,
  chapters jsonb not null default '[]'::jsonb
);
create table if not exists public.participants (
  id bigint generated by default as identity primary key,
  meeting_id bigint not null references public.meetings(id) on delete cascade,
  name text not null
);
create table if not exists public.transcript_segments (
  id bigint generated by default as identity primary key,
  meeting_id bigint not null references public.meetings(id) on delete cascade,
  speaker text not null,
  text text not null,
  start_time integer not null default 0,
  end_time integer not null default 30
);
create table if not exists public.action_items (
  id bigint generated by default as identity primary key,
  meeting_id bigint not null references public.meetings(id) on delete cascade,
  text text not null,
  assignee text not null default 'Unassigned',
  completed boolean not null default false
);
alter table public.meetings enable row level security;
alter table public.participants enable row level security;
alter table public.transcript_segments enable row level security;
alter table public.action_items enable row level security;
create policy "Demo public meetings" on public.meetings for all to anon using (true) with check (true);
create policy "Demo public participants" on public.participants for all to anon using (true) with check (true);
create policy "Demo public transcripts" on public.transcript_segments for all to anon using (true) with check (true);
create policy "Demo public actions" on public.action_items for all to anon using (true) with check (true);

-- Sample meetings displayed immediately after deployment.
insert into public.meetings (title,date,duration,summary,key_topics,chapters) values
('Product Strategy Sync','2026-07-24T09:00:00Z',48,'The team aligned on a focused onboarding milestone and customer validation plan.','["Onboarding","Q3 priorities","Customer research"]','[{"title":"Introductions","timestamp":0},{"title":"Discussion","timestamp":120},{"title":"Next steps","timestamp":480}]'),
('Q3 Marketing Planning','2026-07-23T10:30:00Z',36,'Marketing agreed on campaign themes, owners, and launch milestones.','["Campaign strategy","Content","Launch"]','[{"title":"Introductions","timestamp":0},{"title":"Discussion","timestamp":120}]'),
('Weekly Design Critique','2026-07-22T15:00:00Z',57,'The design team reviewed current flows and captured improvements for the next sprint.','["UX review","Design systems","Sprint planning"]','[{"title":"Introductions","timestamp":0},{"title":"Discussion","timestamp":120}]');

insert into public.participants (meeting_id,name) select id,'Maya Chen' from public.meetings where title='Product Strategy Sync';
insert into public.participants (meeting_id,name) select id,'Alex Morgan' from public.meetings where title='Product Strategy Sync';
insert into public.participants (meeting_id,name) select id,'Sam Lee' from public.meetings where title='Product Strategy Sync';
insert into public.participants (meeting_id,name) select id,'Jordan Kim' from public.meetings where title='Q3 Marketing Planning';
insert into public.participants (meeting_id,name) select id,'Avery Patel' from public.meetings where title='Q3 Marketing Planning';
insert into public.participants (meeting_id,name) select id,'Noah Davis' from public.meetings where title='Weekly Design Critique';
insert into public.participants (meeting_id,name) select id,'Liam Scott' from public.meetings where title='Weekly Design Critique';
insert into public.action_items (meeting_id,text,assignee,completed) select id,'Share the updated plan with the team','Maya Chen',false from public.meetings where title='Product Strategy Sync';
insert into public.action_items (meeting_id,text,assignee,completed) select id,'Schedule customer research sessions','Alex Morgan',true from public.meetings where title='Product Strategy Sync';
insert into public.transcript_segments (meeting_id,speaker,text,start_time,end_time) select id,'Maya Chen','Thanks everyone for joining. Today I want to align on what success looks like for the next milestone.',0,35 from public.meetings where title='Product Strategy Sync';
insert into public.transcript_segments (meeting_id,speaker,text,start_time,end_time) select id,'Alex Morgan','The clearest theme in customer feedback is that new customers need a faster way to get started.',38,83 from public.meetings where title='Product Strategy Sync';
insert into public.transcript_segments (meeting_id,speaker,text,start_time,end_time) select id,'Sam Lee','We can simplify the first-run experience without cutting the core value.',87,130 from public.meetings where title='Product Strategy Sync';
