import { Meeting } from './types';

const base = process.env.NEXT_PUBLIC_SUPABASE_URL;
const anonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
function headers(extra: Record<string,string> = {}) { if (!base || !anonKey || base.includes('your-project')) throw new Error('Add Supabase values to frontend/.env.local.'); return { apikey: anonKey, Authorization: `Bearer ${anonKey}`, ...extra }; }
type RawMeeting = Record<string, any>;
function mapMeeting(raw: RawMeeting): Meeting { return { id: raw.id, title: raw.title, date: raw.date, duration: raw.duration, participants: (raw.participants||[]).map((p:any)=>p.name), summary: raw.summary||'', key_topics: raw.key_topics||[], chapters: raw.chapters||[], transcript: (raw.transcript_segments||[]).sort((a:any,b:any)=>a.start_time-b.start_time), action_items: raw.action_items||[] }; }
const detailSelect='id,title,date,duration,summary,key_topics,chapters,participants(name),transcript_segments(id,speaker,text,start_time,end_time),action_items(id,text,assignee,completed)';
export async function getMeetings(query=''): Promise<Meeting[]> { const filter=query?`&title=ilike.*${encodeURIComponent(query)}*`:''; const r=await fetch(`${base}/rest/v1/meetings?select=${encodeURIComponent('id,title,date,duration,summary,key_topics,chapters,participants(name),action_items(id,text,assignee,completed)')}&order=date.desc${filter}`,{headers:headers(),cache:'no-store'}); if(!r.ok) throw Error('Could not load meetings'); return (await r.json()).map(mapMeeting); }
export async function getMeeting(id:string): Promise<Meeting> { const r=await fetch(`${base}/rest/v1/meetings?select=${encodeURIComponent(detailSelect)}&id=eq.${id}`,{headers:headers(),cache:'no-store'}); if(!r.ok) throw Error('Could not load meeting'); const [meeting]=await r.json(); if(!meeting) throw Error('Meeting not found'); return mapMeeting(meeting); }
export async function createMeeting(data:{title:string;date:string;duration:number;participants:string[]}): Promise<Meeting> { const r=await fetch(`${base}/rest/v1/meetings`,{method:'POST',headers:headers({'Content-Type':'application/json',Prefer:'return=representation'}),body:JSON.stringify({title:data.title,date:data.date,duration:data.duration})}); if(!r.ok) throw Error('Could not save meeting. Check the Supabase database setup.'); const [created]=await r.json(); if(data.participants.length){const people=await fetch(`${base}/rest/v1/participants`,{method:'POST',headers:headers({'Content-Type':'application/json'}),body:JSON.stringify(data.participants.map(name=>({meeting_id:created.id,name})))});if(!people.ok)throw Error('Meeting was saved but participants could not be added.');} return getMeeting(String(created.id)); }
export { base };
